# Generated by Django 5.2.5 on 2026-05-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_unread_orders',
            field=models.BooleanField(default=False, help_text='User has unread order updates'),
        ),
    ]
