# Generated by Django 5.2.5 on 2026-05-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_unread_update',
            field=models.BooleanField(default=False),
        ),
    ]
